# Generated by Django 5.1.2 on 2024-11-09 13:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('v_utilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code_ue', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='The UE code must start with 3 letters followed by 3 or 4 numbers', regex='^[A-Z]{3,4}\\d{3,4}$')], verbose_name='code ue')),
                ('year', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2024, verbose_name='year')),
                ('label', models.CharField(default=None, max_length=50, verbose_name='course label')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('study_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_utilities.studyfield', verbose_name='study field')),
                ('study_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v_utilities.studylevel', verbose_name='studies level')),
                ('teachers', models.ManyToManyField(default=1, limit_choices_to=models.Q(('user_permissions__name', 'teach'), ('is_superuser', True), _connector='OR'), to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(verbose_name='note')),
                ('correcteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='corrector')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manager.course', verbose_name='course')),
                ('owner', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='custom_id')],
            },
        ),
    ]
