# Generated by Django 5.1.2 on 2024-10-22 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('studies_level', models.CharField(choices=[('L1', 'Active'), ('L2', 'Inactive'), ('L3', 'Pending'), ('M1', 'Pending'), ('M2', 'Pending')], default='L1', max_length=2)),
                ('code_ue', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='The UE code must start with 3 letters followed by 3 or 4 numbers', regex='^[A-Z]{3}\\d{3,4}$')], verbose_name='code ue')),
                ('annee', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2024, verbose_name='year')),
                ('intitule', models.CharField(max_length=7, verbose_name='course label')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
