# Generated by Django 5.1.2 on 2025-01-04 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(default=1, limit_choices_to=models.Q(('user_permissions__name', 'teach'), ('is_superuser', True), _connector='OR'), to=settings.AUTH_USER_MODEL, verbose_name='teacher'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='course_manager.course'),
        ),
        migrations.AddField(
            model_name='note',
            name='correcteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='corrector'),
        ),
        migrations.AddField(
            model_name='note',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manager.course', verbose_name='course'),
        ),
        migrations.AddField(
            model_name='note',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='student'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('code_ue', 'year'), name='unique_course'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='custom_id'),
        ),
    ]
