# Generated by Django 5.1.2 on 2024-10-22 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0002_alter_course_intitule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(verbose_name='note')),
                ('correcteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='corrector')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manager.course', verbose_name='course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='custom_id')],
            },
        ),
    ]
