# Generated by Django 5.1.2 on 2024-10-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_options_alter_users_studies_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolrequest',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='processed'),
        ),
    ]
